# Copyright (C) 2016-2017 Bitergia
# GPLv3 License

FROM debian:stretch-slim
MAINTAINER Haiming Lin <lhming23@outlook.com>

ENV DEBIAN_FRONTEND noninteractive
ENV DEPLOY_USER xlab
ENV DEPLOY_USER_DIR /home/${DEPLOY_USER}
ENV CONF_DIR ${DEPLOY_USER_DIR}/conf
ENV SCRIPTS_DIR ${DEPLOY_USER_DIR}/scripts
ENV GRIMOIRELAB_GITEE_RELEASE "0.1.0"

# Initial user
RUN useradd ${DEPLOY_USER} --create-home --shell /bin/bash

# install dependencies
RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        bash locales \
        gcc \
        git git-core \
        python3 \
        python3-pip \
        python3-venv \
        python3-dev \
        python3-gdbm \
        mariadb-client \
        unzip curl wget sudo ssh \
        && \
    apt-get clean && \
    find /var/lib/apt/lists -type f -delete

RUN echo "${DEPLOY_USER} ALL=NOPASSWD: ALL" >> /etc/sudoers

RUN mkdir -p ${DEPLOY_USER_DIR}/logs ; chown -R ${DEPLOY_USER}:${DEPLOY_USER} ${DEPLOY_USER_DIR}/logs
VOLUME ["/home/grimoirelog/logs"]

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

#ADD cacert.pem ${DEPLOY_USER_DIR}/cacert.pem
#RUN CERT_PATH=`python3 -m requests.certs` && \
#    cat ${DEPLOY_USER_DIR}/cacert.pem >> ${CERT_PATH}

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV LANG C.UTF-8

ADD stage ${DEPLOY_USER_DIR}/stage
RUN chmod 755 ${DEPLOY_USER_DIR}/stage

USER ${DEPLOY_USER}

# Do the deployment for GRIMOIRELAB_GITEE_RELEASE

WORKDIR ${DEPLOY_USER_DIR}

RUN mkdir -p ${CONF_DIR} && \
    git clone https://github.com/X-lab2017/grimoirelab.git --depth 1 && \
    cp grimoirelab/default-grimoirelab-settings/setup-secured-gitee.cfg ${CONF_DIR}/setup.cfg && \
    cp grimoirelab/default-grimoirelab-settings/aliases.json ${CONF_DIR}/aliases.json && \
    cp grimoirelab/default-grimoirelab-settings/projects-gitee.json ${CONF_DIR}/projects-gitee.json && \
    cp grimoirelab/default-grimoirelab-settings/identities.yml ${CONF_DIR}/identities.yml && \
    cp grimoirelab/default-grimoirelab-settings/menu.yaml ${CONF_DIR}/menu.yaml && \
    cp grimoirelab/default-grimoirelab-settings/organizations.json ${CONF_DIR}/organizations.json && \
    echo "Installing and checking GrimoireLab Release"

RUN  sudo grimoirelab/utils/build_grimoirelab -l debug --build --install --install_system \
     --relfile grimoirelab/releases/gitee/${GRIMOIRELAB_GITEE_RELEASE} --reposfile grimoirelab/utils/repos-for-gitee.json

HEALTHCHECK --interval=60s --timeout=6s --retries=1 CMD healthcheck.py -c ${CONF_DIR}/setup.cfg -s 'Exception in Task Manager' || exit 1

CMD ${DEPLOY_USER_DIR}/stage